# Site settings
title: Coimbatore Startups Community Curation
email: info@coimbatorestartups.com
description: > # this means to ignore newlines until "baseurl:"
Coimbatore Startups list curated by commmunity members | #KodeKovai | cbestartups | builtinkovai 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://explore.coimbatorestartups.com" # the base hostname & protocol for your site
permalink: /startup/:title
twitter_username: cbestartups
github_username:  kodekovai

# Build settings
markdown: kramdown
